<a href="https://colab.research.google.com/github/lukesilvs/HelloWorld/blob/master/LearningColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction

In [ ]:
print("Hello World")

Hello World


Functions, Conditionals, and Iteration

In [ ]:
def HelloWorldXY(x, y):
  if (x < 10) :
    print("Hello World, x was <10")
  elif (x < 20) :
    print("Hello World, x was <=10 but <20")
  else :
    print("Hello World, x was >=20")
  return x + y

for i in range(8, 25, 5):
  print("Now running with i: {}".format(i))
  r = HelloWorldXY(i,i)
  print("Result From HelloWorld: {}".format(i, r))

Now running with i: 8
Hello World, x was <10
Result From HelloWorld: 8
Now running with i: 13
Hello World, x was <=10 but <20
Result From HelloWorld: 13
Now running with i: 18
Hello World, x was <=10 but <20
Result From HelloWorld: 18
Now running with i: 23
Hello World, x was >=20
Result From HelloWorld: 23


In [ ]:
print(HelloWorldXY(1,2))

Hello World, x was <10
3


In [ ]:
print("Iterate over the items. 'range(2)' is like a list [0,1]")
for i in range(2) :
  print(i)

print("Iterate over an actual list.")
for i in [0,1] :
  print(i)

print("While works")
i = 0
while i < 2 :
  print(i)
  i+=1

Iterate over the items. 'range(2)' is like a list [0,1]
0
1
Iterate over an actual list.
0
1
While works
0
1


In [ ]:
print("Python supports continue and break key words")  
while True : 
  print("Entered while")
  break

Python supports continue and break key words
Entered while


# Numpy and Lists
Python has lists built into the language. However we will use a library called numpy for this. Numpy gives you a lot of support functions that are useful for machine learning.

Here you will see an import statement. This statement makes the entire numpy package available and we can access these symbols using the 'np' syntax.




In [1]:
import numpy as np #make numpy available using np.

# Create a numpy array and append element 
a = np.array(["Hello","World"])
a = np.append(a , "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
  print(i)

print("\nPrinting each element and their index")
for i,e in enumerate(a): # enumerate
  print("Index: {}, was: {}".format(i, e))

Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


In [4]:
print("\nShowing some basic math on arrays")
b = np.array([0,1,4,3,2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max Index: {}".format(np.argmax(b)))


Showing some basic math on arrays
Max: 4
Average: 2.0
Max Index: 2


In [5]:
print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(a), type(a[0])))


You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.str_'>


In [6]:
print("\nUse numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3,  3)
print(c)


Use numpy to create a [3,3] dimension array with random number
[[9.78906498e-01 7.79665413e-04 9.62392970e-01]
 [6.08099076e-01 8.11397674e-01 8.02476736e-01]
 [7.35021444e-01 7.26449393e-01 7.65200466e-01]]


In [7]:
print("\nYou can print the dimension of arrays")
print("Shape of a: {}".format(a.shape)) 
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))
print("...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists")


You can print the dimension of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)
...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists


# Colab Specifics
Colab is a virtual machine you can access directly. To run commands at the VM's terminal, prefix the line with an exclamation point(!)

In [8]:
print("\nDoing $1s on filesystem")
!ls -1
!pwd


Doing $1s on filesystem
sample_data
/content


In [9]:
print("Install numpy")
!pip install numpy

Install numpy
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


**Exercise**
Create a code cell underneath this text cell and add code to:


*   List the path of the current directory
*   Go to /(cd) and list the content(ls-l)



In [12]:
!pwd # list current director
! cd / #change directory
!ls -l #list content

/content
total 4
drwxr-xr-x 1 root root 4096 Jul  6 13:22 sample_data



**Other Notes**
*   Using GPUs may help execute certain course tasks more quickly but dont overuse there is a limit
*  General stuff regarding resetting runtime and clearing outputs

